// @vitest-environment happy-dom
import { readFileSync } from 'node:fs';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { FlightPlanStore } from '../src/flightplan/FlightPlanStore';
import { RouteShapeController } from '../src/flightplan/RouteShapeController';
import { FrequencyPlanner } from '../src/frequencies/FrequencyPlanner';
import { OFPTable } from '../src/components/OFPTable';
import { FrequencyPanel } from '../src/components/FrequencyPanel';
import { SavedPlanRepository, capturePlan } from '../src/flightplan/savedPlans';
import { validateRadioCatalog, type RadioCatalog } from '../src/frequencies/catalog';
const read=(name:string)=>JSON.parse(readFileSync(`${process.cwd()}/public/${name}`,'utf8'));
let data:RadioCatalog;
let refreshFailed = false;
beforeEach(()=>{
  localStorage.clear();vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-05T22:00:00Z'));
  refreshFailed = false;
  data=JSON.parse(readFileSync(`${process.cwd()}/tests/fixtures/aip/northern-radio-areas.json`,'utf8'));data.effectiveDate='2026-09-03';data.nextEffectiveDate=null;data.checkedAt=new Date().toISOString();
  vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{
    const url=String(input);let result;
    if(url.includes('aip-frequencies.json'))result=data;
    else if(url.includes('aip-frequency-status.json'))result={state:refreshFailed ? 'failed' : 'success',effectiveDate:data.effectiveDate,attemptedAt:data.checkedAt};
    else result={...read('aip-aerodromes.json'),effectiveDate:data.effectiveDate};
    return new Response(JSON.stringify(result),{status:200});
  }));
});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
describe('frequency planning integration',()=>{
  it('groups channels for the same service and keeps remarks behind a persistent disclosure', async () => {
    const store = new FlightPlanStore(), planner = new FrequencyPlanner(store);
    const a = store.addWaypoint({lat:69.17833333333334,lon:18.5}, 'ROSSVOLL');
    const b = store.addWaypoint({lat:69.44,lon:18.998611111111114}, 'SELNES');
    store.setPlannedAltitudeFt(a.id,b.id,2500); await planner.reload();
    const root = document.createElement('section'); new FrequencyPanel(root,store,planner,true);
    const first = root.querySelector('.frequency-segment')!;
    expect(first.querySelectorAll(':scope > .frequency-service')).toHaveLength(1);
    expect(first.querySelector('.frequency-candidate')!.textContent).toContain('118.805 / 125.855');
    expect(first.querySelector('.frequency-candidate')!.textContent).not.toContain('For ATS outside opening hours');
    const details = first.querySelector<HTMLDetailsElement>('.frequency-service-details')!;
    expect(details.open).toBe(false);
    expect(details.textContent).toContain('For ATS outside opening hours');
    expect(details.querySelector('a')!.href).toContain('ENR-2.1');
    details.open = true; const key = details.dataset.menuSection;
    store.setManualFrequency(a.id,b.id,'118.805');
    expect(root.querySelector<HTMLDetailsElement>(`[data-menu-section="${key}"]`)!.open).toBe(true);
    expect(root.querySelectorAll('[data-frequency-choice] option[value="118.805"]')).toHaveLength(1);
    expect(root.querySelectorAll('[data-frequency-choice] option[value="125.855"]')).toHaveLength(1);
  });
  it('recomputes a loaded route against refreshed ATS data while retaining the selected OFP channel', async () => {
    const store = new FlightPlanStore(), shapes = new RouteShapeController(store), planner = new FrequencyPlanner(store);
    const a = store.addWaypoint({lat:69.17833333333334,lon:18.5}, 'ROSSVOLL');
    const b = store.addWaypoint({lat:69.44,lon:18.998611111111114}, 'SELNES');
    store.setPlannedAltitudeFt(a.id,b.id,2500); store.setManualFrequency(a.id,b.id,'118.805');
    const repository = new SavedPlanRepository(localStorage), saved = repository.save('Training',capturePlan(store,shapes));
    await planner.reload(); expect(planner.getPlans()[0].segments[0].primary.map(c=>c.channel)).toContain('118.805');
    data.airspaces.find(a=>a.id==='bardufoss-tma')!.channels[0].channel = '119.805';
    repository.load(saved,store,shapes); await planner.reload();
    const plan = planner.getPlans()[0];
    expect(plan.segments[0].primary.map(c=>c.channel)).toContain('119.805');
    expect(plan.segments[0].primary.map(c=>c.channel)).not.toContain('118.805');
    expect(plan.manual).toBe('118.805');
    const root = document.createElement('section'); new FrequencyPanel(root,store,planner,true);
    expect(root.querySelector('[data-frequency-choice] option[value="118.805"]')!.textContent).toContain('Saved selection');
    expect(root.textContent).toContain('Confirm it for this flight');
  });
  it('suggests services on ROSSVOLL to SELNES after a recent refresh failure, and expires that fallback', async () => {
    refreshFailed = true;
    const store = new FlightPlanStore(), planner = new FrequencyPlanner(store);
    const a = store.addWaypoint({ lat: 69.17833333333334, lon: 18.5 }, 'ROSSVOLL');
    const b = store.addWaypoint({ lat: 69.44, lon: 18.998611111111114 }, 'SELNES');
    store.setPlannedAltitudeFt(a.id, b.id, 2500);
    await planner.reload();
    const plan = planner.getPlans()[0];
    expect(plan.note).toBeUndefined();
    expect(plan.notice).toContain('Latest ATS refresh failed');
    const channels = plan.segments.flatMap(s => [...s.primary, ...s.alternatives].map(c => c.channel));
    expect(channels).toContain('118.805');
    expect(channels).toContain('123.755');
    expect(channels).toContain('126.455');
    const element = document.createElement('section');
    new FrequencyPanel(element, store, planner, true);
    expect(element.querySelector('[data-menu-section="suggested-channels"]')!.textContent).toContain('last successful snapshot');
    vi.setSystemTime(new Date('2026-10-08T22:00:00Z'));
    expect(planner.getPlans()[0].segments).toEqual([]);
    expect(planner.getPlans()[0].note).toContain('48 hours');
  });
  it('validates the shipped snapshot and connects current airport channels to route suggestions',async()=>{
    expect(()=>validateRadioCatalog(read('aip-frequencies.json'))).not.toThrow();
    expect(()=>validateRadioCatalog(data)).not.toThrow();
    const store=new FlightPlanStore();const planner=new FrequencyPlanner(store);
    const a=store.addWaypoint({lat:69.05576,lon:18.54036},'ENDU'),b=store.addWaypoint({lat:69.68333,lon:18.91892},'ENTC');
    store.setPlannedAltitudeFt(a.id,b.id,2500);await planner.reload();
    const plan=planner.getPlans()[0];expect(plan.note).toBeUndefined();
    expect(plan.segments[0].primary.map(c=>c.channel)).toContain('118.105');
    expect(plan.segments.at(-1)?.primary.map(c=>c.channel)).toContain('118.305');
    expect(plan.airports.map(c=>c.airport.icao)).toEqual(['ENDU','ENTC']);
    const element=document.createElement('section');new FrequencyPanel(element,store,planner);
    expect(element.textContent).toContain('Route frequencies');expect(element.querySelector('a[href*="ENR-2.1"]')).not.toBeNull();
    store.setManualFrequency(a.id,b.id,'126.455');
    expect(element.textContent).toContain('OFP selection: 126.455');
    element.querySelector<HTMLButtonElement>('[data-frequency-auto]')!.click();
    expect(store.getManualFrequency(a.id,b.id)).toBeNull();
  });
  it('opens the correct sidebar leg from the OFP and shows only its selected channel', async () => {
    const store = new FlightPlanStore(), planner = new FrequencyPlanner(store);
    const a = store.addWaypoint({lat:69,lon:18}, 'ENDU');
    const b = store.addWaypoint({lat:69.3,lon:18.5}, 'Berg');
    const c = store.addWaypoint({lat:69.7,lon:19}, 'ENTC');
    await planner.reload();
    const details = document.createElement('details'), sidebar = document.createElement('section'), ofp = document.createElement('section');
    details.append(sidebar); document.body.append(details, ofp);
    new FrequencyPanel(sidebar, store, planner);
    const table = new OFPTable(ofp, store); store.subscribe(() => table.render()); table.render();
    expect(ofp.querySelector('[data-freq-from]')).toBeNull();
    ofp.querySelectorAll<HTMLButtonElement>('[data-frequency-open-from]')[1].click();
    expect(details.open).toBe(true);
    expect(sidebar.querySelector<HTMLSelectElement>('[data-frequency-leg]')!.value).toBe(`${b.id}->${c.id}`);
    let choice = sidebar.querySelector<HTMLSelectElement>('[data-frequency-choice]')!;
    choice.value = '118.305'; choice.dispatchEvent(new Event('change', {bubbles:true}));
    expect(store.getManualFrequency(b.id,c.id)).toBe('118.305');
    expect(store.getManualFrequency(a.id,b.id)).toBeNull();
    expect(ofp.querySelectorAll('.ofp-frequency-cell')[1].textContent).toBe('118.305Edit');
    expect(ofp.querySelector('.ofp-frequency-segment')).toBeNull();
    choice = sidebar.querySelector<HTMLSelectElement>('[data-frequency-choice]')!;
    expect(choice.value).toBe('118.305');
    choice.value = ''; choice.dispatchEvent(new Event('change', {bubbles:true}));
    expect(store.getManualFrequency(b.id,c.id)).toBeNull();
    expect(ofp.querySelectorAll('.ofp-frequency-cell')[1].textContent).toBe('—Select');
    details.remove(); ofp.remove();
  });
  it('invalidates cached plans when a route is bent and withholds automatic entries when an open tab ages',async()=>{
    const store=new FlightPlanStore();const planner=new FrequencyPlanner(store);const shapes=new RouteShapeController(store);
    const a=store.addWaypoint({lat:69,lon:18},'A'),b=store.addWaypoint({lat:69.7,lon:19},'B');store.setPlannedAltitudeFt(a.id,b.id,4500);
    await planner.reload();const before=planner.getPlans();
    shapes.setLegShape(0,{lat:69.2,lon:17.5});const after=planner.getPlans();
    expect(after).not.toBe(before);expect(after[0].leg.distanceNm).toBeGreaterThan(before[0].leg.distanceNm);
    store.setManualFrequency(a.id,b.id,'126.455');vi.setSystemTime(new Date('2026-10-08T22:00:00Z'));
    expect(planner.getPlans()[0]).toMatchObject({manual:'126.455',segments:[]});
    expect(planner.getStatus()).toContain('withheld');
  });
});
