import type { FlightPlanStore, PlanningSettings } from '../flightplan/FlightPlanStore';
import { C182TPerformanceProvider, pressureAltitudeFromQnh } from '../performance/C182TPerformanceProvider';

interface FieldDefinition { key: keyof PlanningSettings; label: string; suffix: string; min?: number; max?: number; step?: number; }
const FIELDS: FieldDefinition[] = [
  { key:'plannedAltitudeFt', label:'Planned altitude', suffix:'ft', min:0, max:18000, step:100 }, { key:'qnhHpa', label:'QNH', suffix:'hPa', min:850, max:1100, step:0.1 }, { key:'oatC', label:'OAT', suffix:'°C', min:-60, max:50, step:1 }, { key:'rpm', label:'RPM', suffix:'RPM', min:1800, max:2500, step:50 }, { key:'manifoldPressureInHg', label:'Manifold pressure', suffix:'inHg', min:10, max:30, step:0.1 }, { key:'windFromDegTrue', label:'Wind from', suffix:'°T', min:0, max:360, step:1 }, { key:'windSpeedKt', label:'Wind speed', suffix:'kt', min:0, max:150, step:1 }, { key:'variationDegEastPositive', label:'Variation', suffix:'° E(+)/W(-)', min:-30, max:30, step:0.1 },
];
export class PlanningPanel {
  private readonly performanceProvider = new C182TPerformanceProvider();
  constructor(private readonly element: HTMLElement, private readonly store: FlightPlanStore) { this.element.addEventListener('change', (event) => this.handleChange(event)); }
  render(): void {
    const settings = this.store.getSettings(); const pressureAltitudeFt = pressureAltitudeFromQnh(settings.plannedAltitudeFt, settings.qnhHpa); const performance = this.performanceProvider.getCruisePerformance({ pressureAltitudeFt, oatC: settings.oatC, rpm: settings.rpm, manifoldPressureInHg: settings.manifoldPressureInHg });
    this.element.innerHTML = `<div class="planning-title"><div><p class="eyebrow">C182T NAV III · GFC 700 AFCS</p><h2>Cruise planning</h2></div><span class="manual-chip">POH FIG 5-9</span></div><div class="planning-grid">${FIELDS.map((field) => `<label class="planning-field"><span>${field.label}</span><div class="number-input"><input type="number" data-setting="${field.key}" value="${settings[field.key]}" min="${field.min ?? ''}" max="${field.max ?? ''}" step="${field.step ?? 1}" /><b>${field.suffix}</b></div></label>`).join('')}</div><div class="performance-strip"><div>Pressure altitude: <strong>${pressureAltitudeFt.toFixed(0)} ft</strong></div>${performance.status === 'ok' ? `<div>TAS: <strong>${performance.performance.ktas.toFixed(1)} kt</strong></div><div>FF: <strong>${performance.performance.gph.toFixed(2)} GPH</strong></div><div>MCP: <strong>${performance.performance.percentMcp.toFixed(1)}%</strong></div><div>${performance.performance.exactTableEntry ? 'Exact POH entry' : 'Interpolated'}</div>` : `<div class="nav-warning">${performance.warning}</div>`}</div><p class="planning-note">Pressure altitude uses the planning approximation 27 ft per hPa from 1013.25 hPa. OAT is manual in Phase 4. Wind and magnetic variation remain manual until their automatic providers are added.</p>`;
  }
  private handleChange(event: Event): void { const input = event.target as HTMLInputElement; const key = input.dataset.setting as keyof PlanningSettings | undefined; if (!key) return; const value = Number(input.value); if (!Number.isFinite(value)) return; this.store.updateSettings({ [key]: value }); }
}
